// Copyright 2026, Leia Inc.
// SPDX-License-Identifier: BSL-1.0
/*!
 * @file
 * @brief  glTF 2.0 PBR model renderer — raster implementation.
 *
 * Renders the loaded model into an internal colour image with a
 * metallic-roughness PBR pass, then blits that image into the per-eye
 * swapchain viewport region. The viewport-copy + transparency dance mirrors
 * 3dgs_common/gs_renderer.cpp so this drops into the platform code unchanged.
 *
 * v1: material factors only (no textures/IBL), one directional light + flat
 * ambient, static geometry. See ../PORTING.md for the follow-ups.
 */

#include "model_renderer.h"
#include "model_loader.h"

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <vector>

// SPIR-V generated by glslangValidator (--vn) at build time. See CMakeLists.txt.
#include "pbr.vert.h"
#include "pbr.frag.h"

namespace {

VkShaderModule createShaderModule(VkDevice device, const uint32_t* code, size_t sizeBytes) {
    VkShaderModuleCreateInfo ci = {VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};
    ci.codeSize = sizeBytes;
    ci.pCode = code;
    VkShaderModule m = VK_NULL_HANDLE;
    vkCreateShaderModule(device, &ci, nullptr, &m);
    return m;
}

// 4x4 column-major multiply: out = a * b (matches gs_renderer's convention).
void mat4Mul(const float a[16], const float b[16], float out[16]) {
    for (int col = 0; col < 4; ++col)
        for (int row = 0; row < 4; ++row) {
            float s = 0.0f;
            for (int k = 0; k < 4; ++k) s += a[k * 4 + row] * b[col * 4 + k];
            out[col * 4 + row] = s;
        }
}

// A unit cube (24 verts, per-face normals) for loadDebugModel().
void buildCubeModel(ModelData& md) {
    struct V { float p[3], n[3]; };
    const V faces[6][4] = {
        {{{ 0.5f,-0.5f,-0.5f},{1,0,0}},{{ 0.5f, 0.5f,-0.5f},{1,0,0}},{{ 0.5f, 0.5f, 0.5f},{1,0,0}},{{ 0.5f,-0.5f, 0.5f},{1,0,0}}},
        {{{-0.5f,-0.5f, 0.5f},{-1,0,0}},{{-0.5f, 0.5f, 0.5f},{-1,0,0}},{{-0.5f, 0.5f,-0.5f},{-1,0,0}},{{-0.5f,-0.5f,-0.5f},{-1,0,0}}},
        {{{-0.5f, 0.5f,-0.5f},{0,1,0}},{{-0.5f, 0.5f, 0.5f},{0,1,0}},{{ 0.5f, 0.5f, 0.5f},{0,1,0}},{{ 0.5f, 0.5f,-0.5f},{0,1,0}}},
        {{{-0.5f,-0.5f, 0.5f},{0,-1,0}},{{-0.5f,-0.5f,-0.5f},{0,-1,0}},{{ 0.5f,-0.5f,-0.5f},{0,-1,0}},{{ 0.5f,-0.5f, 0.5f},{0,-1,0}}},
        {{{-0.5f,-0.5f, 0.5f},{0,0,1}},{{ 0.5f,-0.5f, 0.5f},{0,0,1}},{{ 0.5f, 0.5f, 0.5f},{0,0,1}},{{-0.5f, 0.5f, 0.5f},{0,0,1}}},
        {{{ 0.5f,-0.5f,-0.5f},{0,0,-1}},{{-0.5f,-0.5f,-0.5f},{0,0,-1}},{{-0.5f, 0.5f,-0.5f},{0,0,-1}},{{ 0.5f, 0.5f,-0.5f},{0,0,-1}}},
    };
    for (int f = 0; f < 6; ++f) {
        uint32_t base = (uint32_t)md.vertices.size();
        for (int i = 0; i < 4; ++i) {
            ModelVertex v{};
            std::memcpy(v.pos, faces[f][i].p, sizeof(v.pos));
            std::memcpy(v.normal, faces[f][i].n, sizeof(v.normal));
            md.vertices.push_back(v);
        }
        const uint32_t idx[6] = {base, base + 1, base + 2, base, base + 2, base + 3};
        md.indices.insert(md.indices.end(), idx, idx + 6);
    }
    ModelMaterial m{};
    m.baseColorFactor[0] = 0.8f; m.baseColorFactor[1] = 0.3f; m.baseColorFactor[2] = 0.2f;
    m.metallic = 0.1f; m.roughness = 0.5f;
    md.materials.push_back(m);

    ModelPrimitive p{};
    p.firstIndex = 0; p.indexCount = (uint32_t)md.indices.size(); p.material = 0;
    const float ident[16] = {1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1};
    std::memcpy(p.modelMatrix, ident, sizeof(ident));
    md.primitives.push_back(p);
    md.primitiveCount = 1;
    md.bboxMin[0] = md.bboxMin[1] = md.bboxMin[2] = -0.5f;
    md.bboxMax[0] = md.bboxMax[1] = md.bboxMax[2] = 0.5f;
    md.hasBBox = true;
}

}  // namespace

// ═════════════════════════════════════════════════════════════════════════
bool ModelRenderer::init(VkInstance instance,
                         VkPhysicalDevice physicalDevice,
                         VkDevice device,
                         VkQueue queue,
                         uint32_t queueFamilyIndex,
                         uint32_t renderWidth,
                         uint32_t renderHeight) {
    instance_ = instance;
    physDevice_ = physicalDevice;
    device_ = device;
    queue_ = queue;
    queueFamily_ = queueFamilyIndex;
    width_ = renderWidth;
    height_ = renderHeight;

    VkCommandPoolCreateInfo poolInfo = {VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};
    poolInfo.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    poolInfo.queueFamilyIndex = queueFamilyIndex;
    if (vkCreateCommandPool(device, &poolInfo, nullptr, &cmdPool_) != VK_SUCCESS) {
        std::fprintf(stderr, "ModelRenderer: failed to create command pool\n");
        return false;
    }

    if (!createRenderTargets()) return false;
    if (!createPipeline()) return false;
    if (!createSamplerAndDefaults()) return false;

    initialized_ = true;
    std::printf("ModelRenderer: initialized (%ux%u)\n", width_, height_);
    return true;
}

bool ModelRenderer::createRenderTargets() {
    // Colour target — also a blit source.
    colorImage_ = modelCreateImage2D(device_, physDevice_, width_, height_, colorFormat_,
        VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT | VK_IMAGE_USAGE_TRANSFER_SRC_BIT);
    if (colorImage_.image == VK_NULL_HANDLE) return false;

    // Depth target — created manually (modelCreateImage2D makes a colour view).
    {
        VkImageCreateInfo ici = {VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
        ici.imageType = VK_IMAGE_TYPE_2D;
        ici.format = depthFormat_;
        ici.extent = {width_, height_, 1};
        ici.mipLevels = 1;
        ici.arrayLayers = 1;
        ici.samples = VK_SAMPLE_COUNT_1_BIT;
        ici.tiling = VK_IMAGE_TILING_OPTIMAL;
        ici.usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;
        ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
        if (vkCreateImage(device_, &ici, nullptr, &depthImage_.image) != VK_SUCCESS) return false;

        VkMemoryRequirements mr;
        vkGetImageMemoryRequirements(device_, depthImage_.image, &mr);
        VkMemoryAllocateInfo ai = {VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};
        ai.allocationSize = mr.size;
        ai.memoryTypeIndex = modelFindMemoryType(physDevice_, mr.memoryTypeBits,
                                                  VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
        if (vkAllocateMemory(device_, &ai, nullptr, &depthImage_.memory) != VK_SUCCESS) return false;
        vkBindImageMemory(device_, depthImage_.image, depthImage_.memory, 0);

        VkImageViewCreateInfo vci = {VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
        vci.image = depthImage_.image;
        vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
        vci.format = depthFormat_;
        vci.subresourceRange = {VK_IMAGE_ASPECT_DEPTH_BIT, 0, 1, 0, 1};
        if (vkCreateImageView(device_, &vci, nullptr, &depthImage_.view) != VK_SUCCESS) return false;
        depthImage_.width = width_;
        depthImage_.height = height_;
    }

    // Render pass: clear colour+depth, leave colour in TRANSFER_SRC for the blit.
    VkAttachmentDescription atts[2] = {};
    atts[0].format = colorFormat_;
    atts[0].samples = VK_SAMPLE_COUNT_1_BIT;
    atts[0].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    atts[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
    atts[0].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    atts[0].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    atts[0].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    atts[0].finalLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;

    atts[1].format = depthFormat_;
    atts[1].samples = VK_SAMPLE_COUNT_1_BIT;
    atts[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
    atts[1].storeOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    atts[1].stencilLoadOp = VK_ATTACHMENT_LOAD_OP_DONT_CARE;
    atts[1].stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE;
    atts[1].initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    atts[1].finalLayout = VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;

    VkAttachmentReference colorRef = {0, VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};
    VkAttachmentReference depthRef = {1, VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};
    VkSubpassDescription sub = {};
    sub.pipelineBindPoint = VK_PIPELINE_BIND_POINT_GRAPHICS;
    sub.colorAttachmentCount = 1;
    sub.pColorAttachments = &colorRef;
    sub.pDepthStencilAttachment = &depthRef;

    VkSubpassDependency deps[2] = {};
    deps[0].srcSubpass = VK_SUBPASS_EXTERNAL;
    deps[0].dstSubpass = 0;
    deps[0].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT;
    deps[0].dstStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT | VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT;
    deps[0].srcAccessMask = 0;
    deps[0].dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT | VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT;
    deps[1].srcSubpass = 0;
    deps[1].dstSubpass = VK_SUBPASS_EXTERNAL;
    deps[1].srcStageMask = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    deps[1].dstStageMask = VK_PIPELINE_STAGE_TRANSFER_BIT;
    deps[1].srcAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    deps[1].dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT;

    VkRenderPassCreateInfo rpci = {VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};
    rpci.attachmentCount = 2;
    rpci.pAttachments = atts;
    rpci.subpassCount = 1;
    rpci.pSubpasses = &sub;
    rpci.dependencyCount = 2;
    rpci.pDependencies = deps;
    if (vkCreateRenderPass(device_, &rpci, nullptr, &renderPass_) != VK_SUCCESS) return false;

    VkImageView fbViews[2] = {colorImage_.view, depthImage_.view};
    VkFramebufferCreateInfo fbci = {VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};
    fbci.renderPass = renderPass_;
    fbci.attachmentCount = 2;
    fbci.pAttachments = fbViews;
    fbci.width = width_;
    fbci.height = height_;
    fbci.layers = 1;
    if (vkCreateFramebuffer(device_, &fbci, nullptr, &framebuffer_) != VK_SUCCESS) return false;

    return true;
}

bool ModelRenderer::createPipeline() {
    // Set-0: one UBO, visible to vertex + fragment.
    VkDescriptorSetLayoutBinding b0 = {};
    b0.binding = 0;
    b0.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    b0.descriptorCount = 1;
    b0.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
    VkDescriptorSetLayoutCreateInfo dlci = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    dlci.bindingCount = 1;
    dlci.pBindings = &b0;
    if (vkCreateDescriptorSetLayout(device_, &dlci, nullptr, &dsLayout_) != VK_SUCCESS) return false;

    // Set 1: per-material textures — base color, MR, normal, occlusion, emissive.
    VkDescriptorSetLayoutBinding mb[5] = {};
    for (uint32_t i = 0; i < 5; ++i) {
        mb[i].binding = i;
        mb[i].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        mb[i].descriptorCount = 1;
        mb[i].stageFlags = VK_SHADER_STAGE_FRAGMENT_BIT;
    }
    VkDescriptorSetLayoutCreateInfo mlci = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    mlci.bindingCount = 5;
    mlci.pBindings = mb;
    if (vkCreateDescriptorSetLayout(device_, &mlci, nullptr, &matSetLayout_) != VK_SUCCESS) return false;

    VkPushConstantRange pcr = {};
    pcr.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;
    pcr.offset = 0;
    pcr.size = sizeof(PushBlock);
    VkDescriptorSetLayout setLayouts[2] = {dsLayout_, matSetLayout_};
    VkPipelineLayoutCreateInfo plci = {VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    plci.setLayoutCount = 2;
    plci.pSetLayouts = setLayouts;
    plci.pushConstantRangeCount = 1;
    plci.pPushConstantRanges = &pcr;
    if (vkCreatePipelineLayout(device_, &plci, nullptr, &pipelineLayout_) != VK_SUCCESS) return false;

    VkShaderModule vs = createShaderModule(device_, pbr_vert_data, sizeof(pbr_vert_data));
    VkShaderModule fs = createShaderModule(device_, pbr_frag_data, sizeof(pbr_frag_data));
    if (vs == VK_NULL_HANDLE || fs == VK_NULL_HANDLE) return false;

    VkPipelineShaderStageCreateInfo stages[2] = {};
    stages[0].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[0].stage = VK_SHADER_STAGE_VERTEX_BIT;
    stages[0].module = vs;
    stages[0].pName = "main";
    stages[1].sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stages[1].stage = VK_SHADER_STAGE_FRAGMENT_BIT;
    stages[1].module = fs;
    stages[1].pName = "main";

    VkVertexInputBindingDescription vib = {0, sizeof(ModelVertex), VK_VERTEX_INPUT_RATE_VERTEX};
    VkVertexInputAttributeDescription via[3] = {
        {0, 0, VK_FORMAT_R32G32B32_SFLOAT, (uint32_t)offsetof(ModelVertex, pos)},
        {1, 0, VK_FORMAT_R32G32B32_SFLOAT, (uint32_t)offsetof(ModelVertex, normal)},
        {2, 0, VK_FORMAT_R32G32_SFLOAT,    (uint32_t)offsetof(ModelVertex, uv)},
    };
    VkPipelineVertexInputStateCreateInfo vi = {VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};
    vi.vertexBindingDescriptionCount = 1;
    vi.pVertexBindingDescriptions = &vib;
    vi.vertexAttributeDescriptionCount = 3;
    vi.pVertexAttributeDescriptions = via;

    VkPipelineInputAssemblyStateCreateInfo ia = {VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};
    ia.topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;

    VkPipelineViewportStateCreateInfo vp = {VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};
    vp.viewportCount = 1;
    vp.scissorCount = 1;

    VkPipelineRasterizationStateCreateInfo rs = {VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};
    rs.polygonMode = VK_POLYGON_MODE_FILL;
    rs.cullMode = VK_CULL_MODE_NONE;       // two-sided shading handles back faces
    rs.frontFace = VK_FRONT_FACE_COUNTER_CLOCKWISE;
    rs.lineWidth = 1.0f;

    VkPipelineMultisampleStateCreateInfo ms = {VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};
    ms.rasterizationSamples = VK_SAMPLE_COUNT_1_BIT;

    VkPipelineDepthStencilStateCreateInfo ds = {VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO};
    ds.depthTestEnable = VK_TRUE;
    ds.depthWriteEnable = VK_TRUE;
    ds.depthCompareOp = VK_COMPARE_OP_LESS;

    VkPipelineColorBlendAttachmentState cba = {};
    cba.colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                         VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT;
    cba.blendEnable = VK_FALSE;
    VkPipelineColorBlendStateCreateInfo cb = {VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};
    cb.attachmentCount = 1;
    cb.pAttachments = &cba;

    VkDynamicState dynStates[2] = {VK_DYNAMIC_STATE_VIEWPORT, VK_DYNAMIC_STATE_SCISSOR};
    VkPipelineDynamicStateCreateInfo dyn = {VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO};
    dyn.dynamicStateCount = 2;
    dyn.pDynamicStates = dynStates;

    VkGraphicsPipelineCreateInfo gpci = {VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};
    gpci.stageCount = 2;
    gpci.pStages = stages;
    gpci.pVertexInputState = &vi;
    gpci.pInputAssemblyState = &ia;
    gpci.pViewportState = &vp;
    gpci.pRasterizationState = &rs;
    gpci.pMultisampleState = &ms;
    gpci.pDepthStencilState = &ds;
    gpci.pColorBlendState = &cb;
    gpci.pDynamicState = &dyn;
    gpci.layout = pipelineLayout_;
    gpci.renderPass = renderPass_;
    gpci.subpass = 0;
    VkResult pr = vkCreateGraphicsPipelines(device_, VK_NULL_HANDLE, 1, &gpci, nullptr, &pipeline_);

    vkDestroyShaderModule(device_, vs, nullptr);
    vkDestroyShaderModule(device_, fs, nullptr);
    if (pr != VK_SUCCESS) {
        std::fprintf(stderr, "ModelRenderer: failed to create pipeline (%d)\n", pr);
        return false;
    }

    // Descriptor pool + set + the host-visible uniform buffer.
    VkDescriptorPoolSize ps = {VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 1};
    VkDescriptorPoolCreateInfo dpci = {VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
    dpci.maxSets = 1;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &ps;
    if (vkCreateDescriptorPool(device_, &dpci, nullptr, &descriptorPool_) != VK_SUCCESS) return false;

    VkDescriptorSetAllocateInfo dsai = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    dsai.descriptorPool = descriptorPool_;
    dsai.descriptorSetCount = 1;
    dsai.pSetLayouts = &dsLayout_;
    if (vkAllocateDescriptorSets(device_, &dsai, &descriptorSet_) != VK_SUCCESS) return false;

    uniformBuffer_ = modelCreateBuffer(device_, physDevice_, sizeof(UniformBlock),
        VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    if (uniformBuffer_.buffer == VK_NULL_HANDLE) return false;

    VkDescriptorBufferInfo dbi = {uniformBuffer_.buffer, 0, sizeof(UniformBlock)};
    VkWriteDescriptorSet w = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
    w.dstSet = descriptorSet_;
    w.dstBinding = 0;
    w.descriptorCount = 1;
    w.descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER;
    w.pBufferInfo = &dbi;
    vkUpdateDescriptorSets(device_, 1, &w, 0, nullptr);
    return true;
}

ModelImage ModelRenderer::uploadTexture(const ModelTexture& tex) {
    ModelImage img;
    if (tex.width <= 0 || tex.height <= 0 || tex.rgba.empty()) return img;
    img.width = tex.width;
    img.height = tex.height;
    const uint32_t w = (uint32_t)tex.width, h = (uint32_t)tex.height;
    const uint32_t mips = (uint32_t)std::floor(std::log2((float)std::max(w, h))) + 1u;

    VkImageCreateInfo ici = {VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};
    ici.imageType = VK_IMAGE_TYPE_2D;
    ici.format = VK_FORMAT_R8G8B8A8_UNORM;  // sRGB decode done in the shader
    ici.extent = {w, h, 1};
    ici.mipLevels = mips;
    ici.arrayLayers = 1;
    ici.samples = VK_SAMPLE_COUNT_1_BIT;
    ici.tiling = VK_IMAGE_TILING_OPTIMAL;
    ici.usage = VK_IMAGE_USAGE_SAMPLED_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT |
                VK_IMAGE_USAGE_TRANSFER_SRC_BIT;  // SRC for mip blits
    ici.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;
    if (vkCreateImage(device_, &ici, nullptr, &img.image) != VK_SUCCESS) return ModelImage{};

    VkMemoryRequirements mr;
    vkGetImageMemoryRequirements(device_, img.image, &mr);
    VkMemoryAllocateInfo ai = {VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};
    ai.allocationSize = mr.size;
    ai.memoryTypeIndex = modelFindMemoryType(physDevice_, mr.memoryTypeBits, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vkAllocateMemory(device_, &ai, nullptr, &img.memory) != VK_SUCCESS) { vkDestroyImage(device_, img.image, nullptr); return ModelImage{}; }
    vkBindImageMemory(device_, img.image, img.memory, 0);

    VkImageViewCreateInfo vci = {VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};
    vci.image = img.image;
    vci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    vci.format = ici.format;
    vci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, mips, 0, 1};
    vkCreateImageView(device_, &vci, nullptr, &img.view);

    // Staging upload of mip 0.
    ModelBuffer staging = modelCreateBuffer(device_, physDevice_, tex.rgba.size(),
        VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
        VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
    void* mapped = nullptr;
    vkMapMemory(device_, staging.memory, 0, tex.rgba.size(), 0, &mapped);
    std::memcpy(mapped, tex.rgba.data(), tex.rgba.size());
    vkUnmapMemory(device_, staging.memory);

    VkCommandBufferAllocateInfo cbai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
    cbai.commandPool = cmdPool_; cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY; cbai.commandBufferCount = 1;
    VkCommandBuffer cmd; vkAllocateCommandBuffers(device_, &cbai, &cmd);
    VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);

    auto barrier = [&](uint32_t mip, uint32_t count, VkImageLayout oldL, VkImageLayout newL,
                       VkAccessFlags srcA, VkAccessFlags dstA, VkPipelineStageFlags srcS, VkPipelineStageFlags dstS) {
        VkImageMemoryBarrier b = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
        b.oldLayout = oldL; b.newLayout = newL;
        b.srcAccessMask = srcA; b.dstAccessMask = dstA;
        b.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED; b.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
        b.image = img.image;
        b.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, mip, count, 0, 1};
        vkCmdPipelineBarrier(cmd, srcS, dstS, 0, 0, nullptr, 0, nullptr, 1, &b);
    };

    // mip 0 → TRANSFER_DST, copy.
    barrier(0, 1, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
            0, VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
    VkBufferImageCopy region = {};
    region.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    region.imageExtent = {w, h, 1};
    vkCmdCopyBufferToImage(cmd, staging.buffer, img.image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

    // Generate mips by successive blits.
    int32_t mw = (int32_t)w, mh = (int32_t)h;
    for (uint32_t i = 1; i < mips; ++i) {
        // src mip (i-1): TRANSFER_DST → TRANSFER_SRC
        barrier(i - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_TRANSFER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
        // dst mip (i): UNDEFINED → TRANSFER_DST
        barrier(i, 1, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                0, VK_ACCESS_TRANSFER_WRITE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT);
        int32_t nw = mw > 1 ? mw / 2 : 1, nh = mh > 1 ? mh / 2 : 1;
        VkImageBlit blit = {};
        blit.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, i - 1, 0, 1};
        blit.srcOffsets[1] = {mw, mh, 1};
        blit.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, i, 0, 1};
        blit.dstOffsets[1] = {nw, nh, 1};
        vkCmdBlitImage(cmd, img.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                       img.image, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &blit, VK_FILTER_LINEAR);
        // src mip (i-1) → SHADER_READ
        barrier(i - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
                VK_ACCESS_TRANSFER_READ_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
        mw = nw; mh = nh;
    }
    // last mip → SHADER_READ
    barrier(mips - 1, 1, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
            VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);

    vkEndCommandBuffer(cmd);
    VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1; si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue_);
    vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
    modelDestroyBuffer(device_, staging);
    return img;
}

bool ModelRenderer::createSamplerAndDefaults() {
    VkSamplerCreateInfo sci = {VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};
    sci.magFilter = VK_FILTER_LINEAR;
    sci.minFilter = VK_FILTER_LINEAR;
    sci.mipmapMode = VK_SAMPLER_MIPMAP_MODE_LINEAR;
    sci.addressModeU = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    sci.addressModeV = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    sci.addressModeW = VK_SAMPLER_ADDRESS_MODE_REPEAT;
    sci.maxLod = VK_LOD_CLAMP_NONE;
    sci.borderColor = VK_BORDER_COLOR_FLOAT_OPAQUE_WHITE;
    if (vkCreateSampler(device_, &sci, nullptr, &sampler_) != VK_SUCCESS) return false;

    ModelTexture white; white.width = 1; white.height = 1; white.rgba = {255, 255, 255, 255};
    whiteTex_ = uploadTexture(white);
    ModelTexture flat;  flat.width = 1;  flat.height = 1;  flat.rgba = {128, 128, 255, 255};
    flatNormalTex_ = uploadTexture(flat);
    return whiteTex_.view != VK_NULL_HANDLE && flatNormalTex_.view != VK_NULL_HANDLE;
}

VkDescriptorSet ModelRenderer::makeMaterialSet(VkImageView baseColor, VkImageView mr,
                                               VkImageView normal, VkImageView occ,
                                               VkImageView emissive) {
    VkDescriptorSetAllocateInfo ai = {VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    ai.descriptorPool = matPool_;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts = &matSetLayout_;
    VkDescriptorSet set = VK_NULL_HANDLE;
    if (vkAllocateDescriptorSets(device_, &ai, &set) != VK_SUCCESS) return VK_NULL_HANDLE;

    VkImageView views[5] = {baseColor, mr, normal, occ, emissive};
    VkDescriptorImageInfo infos[5];
    VkWriteDescriptorSet writes[5];
    for (uint32_t i = 0; i < 5; ++i) {
        infos[i] = {sampler_, views[i], VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};
        writes[i] = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};
        writes[i].dstSet = set;
        writes[i].dstBinding = i;
        writes[i].descriptorCount = 1;
        writes[i].descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
        writes[i].pImageInfo = &infos[i];
    }
    vkUpdateDescriptorSets(device_, 5, writes, 0, nullptr);
    return set;
}

bool ModelRenderer::finalizeModel(ModelData& md) {
    cleanupModel();

    vertexBuffer_ = modelCreateBuffer(device_, physDevice_,
        md.vertices.size() * sizeof(ModelVertex),
        VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    indexBuffer_ = modelCreateBuffer(device_, physDevice_,
        md.indices.size() * sizeof(uint32_t),
        VK_BUFFER_USAGE_INDEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
        VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);
    if (vertexBuffer_.buffer == VK_NULL_HANDLE || indexBuffer_.buffer == VK_NULL_HANDLE) return false;
    modelUploadBuffer(device_, physDevice_, queue_, cmdPool_, vertexBuffer_,
                      md.vertices.data(), vertexBuffer_.size);
    modelUploadBuffer(device_, physDevice_, queue_, cmdPool_, indexBuffer_,
                      md.indices.data(), indexBuffer_.size);

    // Upload textures (parallel to md.textures; empty entries stay null).
    modelTextures_.resize(md.textures.size());
    for (size_t i = 0; i < md.textures.size(); ++i)
        if (!md.textures[i].rgba.empty())
            modelTextures_[i] = uploadTexture(md.textures[i]);

    materials_ = std::move(md.materials);
    primitives_ = std::move(md.primitives);
    std::memcpy(bboxMin_, md.bboxMin, sizeof(bboxMin_));
    std::memcpy(bboxMax_, md.bboxMax, sizeof(bboxMax_));
    hasBBox_ = md.hasBBox;
    numPrimitives_ = md.primitiveCount;

    // Per-material descriptor sets (set = 1) + a default for material == -1.
    const uint32_t nSets = (uint32_t)materials_.size() + 1;
    VkDescriptorPoolSize ps = {VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, nSets * 5};
    VkDescriptorPoolCreateInfo dpci = {VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
    dpci.maxSets = nSets;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &ps;
    if (vkCreateDescriptorPool(device_, &dpci, nullptr, &matPool_) != VK_SUCCESS) return false;

    auto viewOr = [&](int idx, VkImageView def) -> VkImageView {
        if (idx >= 0 && idx < (int)modelTextures_.size() && modelTextures_[idx].view != VK_NULL_HANDLE)
            return modelTextures_[idx].view;
        return def;
    };
    materialSets_.reserve(materials_.size());
    for (const auto& m : materials_) {
        materialSets_.push_back(makeMaterialSet(
            viewOr(m.baseColorTex, whiteTex_.view),
            viewOr(m.metallicRoughnessTex, whiteTex_.view),
            viewOr(m.normalTex, flatNormalTex_.view),
            viewOr(m.occlusionTex, whiteTex_.view),
            viewOr(m.emissiveTex, whiteTex_.view)));
    }
    defaultMatSet_ = makeMaterialSet(whiteTex_.view, whiteTex_.view, flatNormalTex_.view,
                                     whiteTex_.view, whiteTex_.view);

    modelLoaded_ = true;
    return true;
}

bool ModelRenderer::loadModel(const char* gltfPath) {
    if (!initialized_ || !gltfPath) return false;
    ModelData md;
    if (!model_loader_load(gltfPath, md)) return false;
    if (!finalizeModel(md)) return false;
    loadedModelPath_ = gltfPath;
    return true;
}

bool ModelRenderer::loadDebugModel() {
    if (!initialized_) return false;
    ModelData md;
    buildCubeModel(md);
    if (!finalizeModel(md)) return false;
    loadedModelPath_ = "<debug-cube>";
    return true;
}

bool ModelRenderer::hasModel() const { return modelLoaded_; }
const std::string& ModelRenderer::modelPath() const { return loadedModelPath_; }
uint32_t ModelRenderer::primitiveCount() const { return numPrimitives_; }

bool ModelRenderer::getSceneBBox(float outMin[3], float outMax[3]) const {
    if (!modelLoaded_ || !hasBBox_) return false;
    std::memcpy(outMin, bboxMin_, sizeof(bboxMin_));
    std::memcpy(outMax, bboxMax_, sizeof(bboxMax_));
    return true;
}

bool ModelRenderer::getRobustSceneBounds(float, float,
                                         float outCenter[3], float outExtent[3]) const {
    float mn[3], mx[3];
    if (!getSceneBBox(mn, mx)) return false;
    for (int i = 0; i < 3; ++i) {
        outCenter[i] = 0.5f * (mn[i] + mx[i]);
        outExtent[i] = mx[i] - mn[i];
    }
    return true;
}

bool ModelRenderer::pickSurface(const float[3], const float[3], float[3], float) const {
    // TODO(follow-up): ray/triangle intersection against the loaded mesh.
    return false;
}

float ModelRenderer::findBestYaw(const float[3], const float[3], uint32_t) const {
    return 0.0f;  // glTF models are authored front-facing.
}

void ModelRenderer::updateUniforms(const float viewMatrix[16], const float projMatrix[16],
                                   float clipFar) {
    // Mirror gs_renderer: flip world Y at the view stage (right-multiply by
    // diag(1,-1,1,1) → negate view column 1) so the model is upright and
    // consistent with the demo's Y-mirrored display-pose contract.
    float vmFlipped[16];
    std::memcpy(vmFlipped, viewMatrix, sizeof(vmFlipped));
    vmFlipped[4] = -vmFlipped[4];
    vmFlipped[5] = -vmFlipped[5];
    vmFlipped[6] = -vmFlipped[6];
    vmFlipped[7] = -vmFlipped[7];

    UniformBlock ub{};
    mat4Mul(projMatrix, vmFlipped, ub.viewProj);

    // View matrix with the Z row negated → positive Z = forward (matches
    // gs_renderer / the eye_display.z forward distance), used by the shader's
    // foreground clip. Column-major Z-row indices: 2, 6, 10, 14.
    std::memcpy(ub.view, vmFlipped, sizeof(ub.view));
    ub.view[2]  = -ub.view[2];
    ub.view[6]  = -ub.view[6];
    ub.view[10] = -ub.view[10];
    ub.view[14] = -ub.view[14];

    // Camera world position = -R^T * t from the flipped view matrix.
    float tx = vmFlipped[12], ty = vmFlipped[13], tz = vmFlipped[14];
    ub.cameraPos[0] = -(vmFlipped[0] * tx + vmFlipped[1] * ty + vmFlipped[2] * tz);
    ub.cameraPos[1] = -(vmFlipped[4] * tx + vmFlipped[5] * ty + vmFlipped[6] * tz);
    ub.cameraPos[2] = -(vmFlipped[8] * tx + vmFlipped[9] * ty + vmFlipped[10] * tz);
    ub.cameraPos[3] = 1.0f;

    // Fixed key light (world space), normalized.
    float lx = 0.4f, ly = 0.8f, lz = 0.5f;
    float ln = std::sqrt(lx * lx + ly * ly + lz * lz);
    ub.lightDir[0] = lx / ln; ub.lightDir[1] = ly / ln; ub.lightDir[2] = lz / ln;
    ub.lightDir[3] = (clipFar > 0.0f) ? clipFar : 0.0f;  // foreground clip (view-space)

    void* mapped = nullptr;
    vkMapMemory(device_, uniformBuffer_.memory, 0, sizeof(UniformBlock), 0, &mapped);
    std::memcpy(mapped, &ub, sizeof(UniformBlock));
    vkUnmapMemory(device_, uniformBuffer_.memory);
}

void ModelRenderer::renderEye(VkImage swapchainImage,
                              VkFormat /*swapchainFormat*/,
                              uint32_t /*imageWidth*/,
                              uint32_t /*imageHeight*/,
                              uint32_t viewportX,
                              uint32_t viewportY,
                              uint32_t viewportWidth,
                              uint32_t viewportHeight,
                              const float viewMatrix[16],
                              const float projMatrix[16],
                              bool transparentBg,
                              float clipFarViewSpace) {
    if (!initialized_ || !modelLoaded_) return;

    updateUniforms(viewMatrix, projMatrix, clipFarViewSpace);

    VkCommandBufferAllocateInfo ai = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
    ai.commandPool = cmdPool_;
    ai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    ai.commandBufferCount = 1;
    VkCommandBuffer cmd;
    vkAllocateCommandBuffers(device_, &ai, &cmd);
    VkCommandBufferBeginInfo bi = {VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);

    VkClearValue clears[2];
    if (transparentBg) clears[0].color = {{0.0f, 0.0f, 0.0f, 0.0f}};
    else               clears[0].color = {{0.05f, 0.05f, 0.06f, 1.0f}};
    clears[1].depthStencil = {1.0f, 0};

    VkRenderPassBeginInfo rpbi = {VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};
    rpbi.renderPass = renderPass_;
    rpbi.framebuffer = framebuffer_;
    rpbi.renderArea.offset = {0, 0};
    rpbi.renderArea.extent = {viewportWidth, viewportHeight};
    rpbi.clearValueCount = 2;
    rpbi.pClearValues = clears;
    vkCmdBeginRenderPass(cmd, &rpbi, VK_SUBPASS_CONTENTS_INLINE);

    VkViewport vpRect = {0.0f, 0.0f, (float)viewportWidth, (float)viewportHeight, 0.0f, 1.0f};
    VkRect2D scissor = {{0, 0}, {viewportWidth, viewportHeight}};
    vkCmdSetViewport(cmd, 0, 1, &vpRect);
    vkCmdSetScissor(cmd, 0, 1, &scissor);

    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipeline_);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayout_,
                            0, 1, &descriptorSet_, 0, nullptr);
    VkDeviceSize voff = 0;
    vkCmdBindVertexBuffers(cmd, 0, 1, &vertexBuffer_.buffer, &voff);
    vkCmdBindIndexBuffer(cmd, indexBuffer_.buffer, 0, VK_INDEX_TYPE_UINT32);

    for (const auto& p : primitives_) {
        PushBlock pb{};
        std::memcpy(pb.model, p.modelMatrix, sizeof(pb.model));
        ModelMaterial m;  // defaults if material == -1
        if (p.material >= 0 && p.material < (int)materials_.size()) m = materials_[p.material];
        std::memcpy(pb.baseColorFactor, m.baseColorFactor, sizeof(pb.baseColorFactor));
        pb.mrParams[0] = m.metallic;
        pb.mrParams[1] = m.roughness;
        pb.emissive[0] = m.emissive[0];
        pb.emissive[1] = m.emissive[1];
        pb.emissive[2] = m.emissive[2];
        vkCmdPushConstants(cmd, pipelineLayout_,
                           VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                           0, sizeof(PushBlock), &pb);

        // Set 1: this primitive's material textures (or the all-defaults set).
        VkDescriptorSet matSet =
            (p.material >= 0 && p.material < (int)materialSets_.size())
                ? materialSets_[p.material] : defaultMatSet_;
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayout_,
                                1, 1, &matSet, 0, nullptr);

        vkCmdDrawIndexed(cmd, p.indexCount, 1, p.firstIndex, 0, 0);
    }

    vkCmdEndRenderPass(cmd);
    // colorImage_ is now in TRANSFER_SRC_OPTIMAL (render-pass finalLayout).

    // Swapchain → TRANSFER_DST. First eye (vpX==0): UNDEFINED ok. Second eye:
    // preserve the first by treating the prior contents as COLOR_ATTACHMENT.
    VkImageMemoryBarrier toDst = {VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};
    toDst.srcAccessMask = (viewportX == 0) ? 0 : VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    toDst.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    toDst.oldLayout = (viewportX == 0) ? VK_IMAGE_LAYOUT_UNDEFINED
                                       : VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    toDst.newLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    toDst.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toDst.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    toDst.image = swapchainImage;
    toDst.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         0, 0, nullptr, 0, nullptr, 1, &toDst);

    // Blit [0,0]-[vpW,vpH] of the internal image into the swapchain viewport
    // (handles RGBA→BGRA format conversion, matching gs_renderer).
    VkImageBlit blit = {};
    blit.srcSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    blit.srcOffsets[0] = {0, 0, 0};
    blit.srcOffsets[1] = {(int32_t)viewportWidth, (int32_t)viewportHeight, 1};
    blit.dstSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    blit.dstOffsets[0] = {(int32_t)viewportX, (int32_t)viewportY, 0};
    blit.dstOffsets[1] = {(int32_t)(viewportX + viewportWidth),
                          (int32_t)(viewportY + viewportHeight), 1};
    vkCmdBlitImage(cmd,
        colorImage_.image, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
        swapchainImage, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
        1, &blit, VK_FILTER_LINEAR);

    // Swapchain → COLOR_ATTACHMENT_OPTIMAL for the compositor.
    VkImageMemoryBarrier toColor = toDst;
    toColor.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
    toColor.dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;
    toColor.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;
    toColor.newLayout = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                         VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
                         0, 0, nullptr, 0, nullptr, 1, &toColor);

    vkEndCommandBuffer(cmd);
    VkSubmitInfo si = {VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    vkQueueSubmit(queue_, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(queue_);
    vkFreeCommandBuffers(device_, cmdPool_, 1, &cmd);
}

void ModelRenderer::cleanupModel() {
    if (vertexBuffer_.buffer != VK_NULL_HANDLE) modelDestroyBuffer(device_, vertexBuffer_);
    if (indexBuffer_.buffer != VK_NULL_HANDLE) modelDestroyBuffer(device_, indexBuffer_);
    for (auto& t : modelTextures_)
        if (t.image != VK_NULL_HANDLE) modelDestroyImage(device_, t);
    modelTextures_.clear();
    // Freeing the pool frees all material sets allocated from it.
    if (matPool_ != VK_NULL_HANDLE) { vkDestroyDescriptorPool(device_, matPool_, nullptr); matPool_ = VK_NULL_HANDLE; }
    materialSets_.clear();
    defaultMatSet_ = VK_NULL_HANDLE;
    materials_.clear();
    primitives_.clear();
    hasBBox_ = false;
    numPrimitives_ = 0;
    modelLoaded_ = false;
    loadedModelPath_.clear();
}

void ModelRenderer::cleanup() {
    if (!initialized_ && cmdPool_ == VK_NULL_HANDLE) return;
    if (device_ != VK_NULL_HANDLE) vkDeviceWaitIdle(device_);

    cleanupModel();

    if (sampler_ != VK_NULL_HANDLE) { vkDestroySampler(device_, sampler_, nullptr); sampler_ = VK_NULL_HANDLE; }
    if (whiteTex_.image != VK_NULL_HANDLE) modelDestroyImage(device_, whiteTex_);
    if (flatNormalTex_.image != VK_NULL_HANDLE) modelDestroyImage(device_, flatNormalTex_);
    if (matSetLayout_ != VK_NULL_HANDLE) { vkDestroyDescriptorSetLayout(device_, matSetLayout_, nullptr); matSetLayout_ = VK_NULL_HANDLE; }
    if (uniformBuffer_.buffer != VK_NULL_HANDLE) modelDestroyBuffer(device_, uniformBuffer_);
    if (descriptorPool_ != VK_NULL_HANDLE) { vkDestroyDescriptorPool(device_, descriptorPool_, nullptr); descriptorPool_ = VK_NULL_HANDLE; }
    if (pipeline_ != VK_NULL_HANDLE) { vkDestroyPipeline(device_, pipeline_, nullptr); pipeline_ = VK_NULL_HANDLE; }
    if (pipelineLayout_ != VK_NULL_HANDLE) { vkDestroyPipelineLayout(device_, pipelineLayout_, nullptr); pipelineLayout_ = VK_NULL_HANDLE; }
    if (dsLayout_ != VK_NULL_HANDLE) { vkDestroyDescriptorSetLayout(device_, dsLayout_, nullptr); dsLayout_ = VK_NULL_HANDLE; }
    if (framebuffer_ != VK_NULL_HANDLE) { vkDestroyFramebuffer(device_, framebuffer_, nullptr); framebuffer_ = VK_NULL_HANDLE; }
    if (renderPass_ != VK_NULL_HANDLE) { vkDestroyRenderPass(device_, renderPass_, nullptr); renderPass_ = VK_NULL_HANDLE; }
    if (colorImage_.image != VK_NULL_HANDLE) modelDestroyImage(device_, colorImage_);
    if (depthImage_.image != VK_NULL_HANDLE) modelDestroyImage(device_, depthImage_);
    if (cmdPool_ != VK_NULL_HANDLE) { vkDestroyCommandPool(device_, cmdPool_, nullptr); cmdPool_ = VK_NULL_HANDLE; }

    initialized_ = false;
}

ModelRenderer::~ModelRenderer() { cleanup(); }
